fix(Constructor): fix bugs
consta-design-system/theme-constructor pull request #1
Opened 2023-04-09 11:58 UTC by N1MBER

consta-design-system/uikit#2984

2023-04-18 09:12 UTC, BagenovA requested changes

2023-04-18 09:12 UTC, BagenovA commented on src/components/Menu/Menu.tsx
> +        content="Вы точно хотите покинуть страницу? Изменения в текущей теме не будут сохранены"
Может так: Вы действительно хотите закрыть страницу? Изменения будут утеряны, если их не сохранить.

2023-04-18 09:12 UTC, BagenovA commented on src/components/Menu/Menu.tsx
> +            label: 'Уйти',
Может лучше: "Закрыть" или "Выйти"

2023-04-18 09:12 UTC, BagenovA commented on src/pages/Constructor/ConstructorExample/ConstructorExampleAnalytic/ConstructorExampleAnalytic.tsx
> +        Здесь вы можете ознакомиться с аналитикой по работе команд.
Вариант: Посмотреть аналитику по работе команд

2023-04-18 09:12 UTC, BagenovA commented on src/pages/Constructor/ConstructorExample/ConstructorExampleAnalytic/ConstructorExampleAnalytic.tsx
> +        <Tooltip anchorRef={buttonRef}>Настроить дешборд по аналитике</Tooltip>
Заменить на: Настроить дашборд по аналитике

2023-04-18 09:12 UTC, BagenovA commented on src/pages/Constructor/ConstructorExample/ConstructorExampleChart/ConstructorExampleChart.tsx
> +        График показывает количество выполненных командой задач за определённую
Заменить на: График показывает количество выполненных задач за определённый отрезок времени.

2023-04-18 09:12 UTC, BagenovA commented on src/pages/Constructor/ConstructorExample/ConstructorExampleChart/ConstructorExampleChart.tsx
> +        Выполненных задач
Может так: Выполненные задачи

2023-04-18 09:12 UTC, BagenovA commented on src/utils/theme/colors.ts
>      description: 'Цвет молока',
Что значит "Цвет молока?"

2023-04-18 09:12 UTC, BagenovA commented on src/utils/theme/colors.ts
>      description: 'Цвет фона бордеров котрола',
Исправить ошибку в слове "контрола"

2023-04-18 18:24 UTC, Lyubavskaya reviewed
В шрифтах не выбрать другой шрифт

2023-04-20 12:30 UTC, gizeasy requested changes

2023-04-20 12:30 UTC, gizeasy commented on src/modules/colors/index.ts
>  export const colorDarkAtom = atom<ColorBase>(defaultDarkColors);
Сейчас при изменении одного цвета идет пересчет всех цветов, по хорошему надо имеет на каждое поле ввода свой атом, таким образом при изменении одного атома будет пересчитыватся только 1 цвет.

2023-04-20 12:30 UTC, gizeasy commented on src/modules/colors/index.ts
>  onUpdate(colorLightAtom, (ctx, value) => {
Не совсем верная логика обновлять атом при изменнении другого, такое нужно делать когда нет прямой зависимости, а тут есть, по этому лучше создать атом который будет подписан на все переменные, 

```
const autoSavePresetAtom = atom((ctx) => {
 const prop = ctx.spy(propAtom)
});
```

далее такой атом можно обернуть в дебоунс для обновление всего интерфейса с задежкой 
и для сохранения атома с задержкой

2023-04-20 12:30 UTC, gizeasy commented on src/modules/colors/index.ts
>  export const colorDarkAtom = atom<ColorBase>(defaultDarkColors);
Подумай в сторону фабрики для создания груп атомов сразу с описынными связями
к примеру createColorProp('name')
в нем сразу создлавать все необходимые атомы и их связи

2023-04-20 12:30 UTC, gizeasy commented on src/pages/Constructor/ConstructorHeader/ConstructorHeader.tsx
>    const setTheme = useAction((ctx, value: ThemePreset) =>
не обязательно писать функцию 

```
const setTheme = useAction((ctx, value: ThemePreset) => themeAtom(ctx, value))

// эквивалено

const setTheme = useAction(themeAtom)

// эквивалено

const [theme, setTheme] = useAtom(themeAtom);
```


Много где без нужды исползуешь `useAction` лучше забирать сразу из useAtom `const [theme, setTheme] = useAtom(themeAtom);`

2023-04-20 14:38 UTC, merged