Fix/constructor
consta-design-system/theme-constructor pull request #2
Opened 2023-05-16 13:39 UTC by N1MBER

closes consta-design-system/uikit#3015

2023-05-18 07:57 UTC, gizeasy requested changes
Очень странно ведут себя маски, еще возможно нужно их сокращать количество знаков поле запятой

https://github.com/consta-design-system/theme-constructor/assets/13190808/699d76dd-dbe5-4a44-ad1a-1109ea68c58b

2023-05-18 08:00 UTC, gizeasy requested changes
Можно сломать маску rgba

https://github.com/consta-design-system/theme-constructor/assets/13190808/75431385-9d56-4efc-8264-2b3a4da649ca

2023-05-18 08:05 UTC, gizeasy requested changes
Прыгает текст при изменении любого поля, возможно связано с тем что в загружается новый шрифт интер и он переопределяет шрифт который в консте

https://github.com/consta-design-system/theme-constructor/assets/13190808/443b3d8a-39b1-45cb-9baa-b96d94d94b87

2023-05-18 08:11 UTC, gizeasy requested changes
при переключении темы на темную, тема примера интерфейса не меняется

![image](https://github.com/consta-design-system/theme-constructor/assets/13190808/829e3d86-c6a6-44f4-9193-ff43572a49b7)

2023-05-18 09:01 UTC, hell0anna commented
что-то случилось с иконкой сохранения
<img width="293" alt="image" src="https://github.com/consta-design-system/theme-constructor/assets/51019093/a048dfde-bbc7-4d99-8491-95e8c1ab6665">

2023-05-23 08:39 UTC, gizeasy requested changes
![image](https://github.com/consta-design-system/theme-constructor/assets/13190808/8a4cb060-5677-4e5f-9e61-335ad7b6ccee)

сделай чтоб ссылка всегда открывалась в новой вкладке

2023-05-23 08:40 UTC, gizeasy requested changes
![image](https://github.com/consta-design-system/theme-constructor/assets/13190808/bf729dca-c231-4bac-8528-a02549136209)

Имеется полоса скрола хотя контент весь вмещается

2023-05-23 08:43 UTC, gizeasy requested changes
![image](https://github.com/consta-design-system/theme-constructor/assets/13190808/58e5e922-d756-4afa-b73e-65287b32540e)

ссылки на портал и гайд не работают, используй useLink или link для составления ссылки

2023-05-23 11:04 UTC, merged